### ISSUE TITLE
Which subsets of CONUS404 data should we include in our various storage locations?

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#106]
Starting a thread to discuss which subsets of data we want in various locations. This discussion hinges on #105 - so let's reach consensus there first. Here's a first guess, but I'd like input from @rsignell-usgs, @rviger-usgs. (FYI for @kadunne-usgs)

**ScienceBase page with Black Pearl-GLOBUS endpoint**
- all data files on Black Pearl - this can be our formal mechanism for providing access to the entire dataset

**Amazon Open Data Sponsorship**
- subset of "useful" daily variables (that we currently have on S3)
- subset of "useful" hourly variables (that we currently have on S3)
- subset of bias-corrected "useful" daily variables (that we currently have on S3)
- subset of bias-corrected "useful" hourly variables (that we currently have on S3)

**Open Storage Network Pod**
- aggregated versions of the datasets need by HyTEST eval, IWAAs, NWC, etc.

**Comment by rviger-usgs** [comment]
re: variables we currently have on S3, it'd be good to: 

1. make sure [this Sharepoint page](https://doimspp.sharepoint.com/sites/gs-wma-hytest/SitePages/CONUS404-Initial-Variables.aspx?source=https%3a//doimspp.sharepoint.com/sites/gs-wma-hytest/SitePages/Forms/ByAuthor.aspx) is consistent w/what's available on our internal S3 bucket and what will be shared via Amazon ODS. 
2. understand which variables in the list from the PUMP DRB folks and from NCAR are NOT present and figure out a plan for those (even if only to say, "no, those aren't included"). I'll add Krista, since I think she has been tracking variable lists, to this thread and update shortly...
