### ISSUE TITLE
Creation of CONUS404 cutouts for calibration of nat'l WRF-Hydro application

### ISSUE THREAD

**Issue by rviger-usgs** [hytest-org/hytest#109]
User needs to make many small subsets from the CONUS404 for a handful (~10) variables. Operating on their (NCAR Cheyenne) HPC is more time-intensive than desired.  100 basins and it took about 7k core hours. So total would be about 100 K core hours, which would probably delay project timelines.

Looking for ways to speed this up either on Cheyenne or on USGS Denali HPC. 

Seems like the technical challenge is how to parallelize millions of ncks commands to subset netcdf files and do so without really inefficiently consuming nodes on the platform.

Jeff Falgout offered a few suggestions , via USGS Team for "Denali Help" (today, 11/7; can't provide URL): 

1. to wrap srun in a for loop and send the srun command to the background
2. Use the --multi-prog option. https://slurm.schedmd.com/srun.html#SECTION_MULTIPLE-PROGRAM-CONFIGURATION
3. Use job packing. https://slurm.schedmd.com/heterogeneous_jobs.html and https://slurm.schedmd.com/SLUG16/Job_Packs_SUG_2016.pdf

@arezoorn is looking into Jeff's suggestions now. @gochis and @ishita9 also part of this thread.

**Comment by rviger-usgs** [comment]
@arezoorn @rsignell-usgs @amsnyder, 
should we be talking to the Denali folks about reserving some nodes/getting queue priority for this short-term burst of work?

**Comment by arezoorn** [comment]
That would be great if possible. I am IO bound right now in this pre-calibration task, so I cannot do many jobs at once, but I think it would be helpful to get dedicated resources so I this could continue without interruption at least. Right now, one problem is that since the queue is unexpected, the jobs are remaining in the queue and getting submitted at once and therefore putting lots of IO on the system and results in slow down.

**Comment by arezoorn** [comment]
A update, I made modification to my script to submit a big job instead of many tiny ones. This will help with management of the jobs in the queue.

**Comment by arezoorn** [comment]
@rviger-usgs Update, the modified workflow is doing a decent job. I can finish the subsetting of the forcing files by next week with this speed. It is pushing the calibration start to next week, but that is fine since I would need time to test the calibration workflow on Denali after Ishita is done with the testing. So I think we can now close this issue.

**Comment by arezoorn** [comment]
I am not sure if I get your question correctly but let me try to answer and if it does not, let me know. I have already cutout some of the forcing on Cheyenne (about 300 basins), and the rest is happening on Denali (150 basins done so far). The rest of the basins will be done by next week and they are running on Denali. 

According to my schedule, I was going to start the calibration mid this week, but it is now pushed to early next week. There is some time that I could save in the calibration phase (with optimization of our calibration workflow) and that should compensate for the delay in the start of the calibration due to our problems in the preparation phase. 

I hope this helps to clarify things.

**Comment by rviger-usgs** [comment]
that's perfectly clear. thanks @arezoorn. 

should we close this issue?

**Comment by arezoorn** [comment]
Yes, we can close this issue. Thanks!

**Comment by rviger-usgs** [comment]
closed.
