### ISSUE TITLE
0 values in Streamflow and Else

### ISSUE THREAD

**Issue by sfoks** [hytest-org/hytest#11]
We need to decide on a way forward with handling zeroflow, zero values when doing log transformations. We can add 0.01 cfs to every 0 flow or use something else. Sydney to talk with Erin, @thodson-usgs.

Also should this be a "preprocessing" step or keep it in the stats packages? 

@gzt5142 can show some code snippets.

**Comment by thodson-usgs** [comment]
Neither. Handle zeros in the notebook where we compute the benchmark metrics. 

Adding 0.01 cfs is a reasonable hack. Eventually, I'd like to move towards compound likelihoods, but that's d-score v2.

**Comment by thodson-usgs** [comment]
They're all wrong, but Tim/Rich is simplest and best for now, IMO.

**Comment by gzt5142** [comment]
sweet... will continue to use clip/clamp... 

Incidentally, numpy `clip()` is faster than `where()` in this use-case.  
```text
threshold=0.01
%timeit _ = df['obs'].clip(threshold)
293 µs ± 4.42 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

%timeit _ = df.where(df > threshold, threshold)
527 µs ± 6.27 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

len(df.index)
12145
```

`where()` is the **much** more flexible tool for boolean selectors... but for this straightforward minimum-value threshold use-case, `clip()` works faster, because it has a simpler mandate (and benefits from some optimizations within the `numpy` lib).  

Same results -- so correct answers either way -- but for a process that benefits from incremental speed increases, consider `clip()`.

**Comment by gzt5142** [comment]
seems like this is sorted.... closing.
