### ISSUE TITLE
Build JupyterBook TOC

### ISSUE THREAD

**Issue by gzt5142** [hytest-org/hytest#118]
The JB demo I did a few weeks back showed the essentials for how a collection of notebooks can be turned into a 'book' website.  Now that we have some of those notebooks finalized, it may be time to start thinking about how the table of contents (TOC) should be organized to build that book. 

A few thoughts: 

- TOC is not tied to the folder/file structure within the repo (although it can be). 
- A file in the repo won't show up in the compiled book unless it has an entry in the TOC
- TOC can be set up as an outline, with arbitrary number of levels. For practical purposes, 3 or maybe 4 level is as deep as it should go. (this affects how the TOC is rendered in the left panel/frame in the book).

**Comment by gzt5142** [comment]
The jupyterbook documentation itself is a good reference and example. 

The JB docs are at: https://jupyterbook.org/en/stable/intro.html
The TOC to create that structure/menu on the left panel is at https://github.com/executablebooks/jupyter-book/blob/master/docs/_toc.yml

BOOK is composed of one or more PARTS
PARTS are composed of one or more CHAPTERS
CHAPTERS can either be stand-alone or be composed from multiple SECTIONS
SECTIONS can themselves contain SECTIONS (i.e. sub-sections).

**Comment by gzt5142** [comment]
@amsnyder -- I've got a more complete TOC example in this branch (in `_toc.yml`), which I think will serve as a useful starting point to sketch out the initial book organization. I just filled in some ideas centered around the specific notebooks that I worked on...  it will need your larger vision to add in the rest of the material and reshape it into a coherent whole.

**Comment by gzt5142** [comment]
Related to TOC and jupyterbook building -- 

This TOC and template were based on the project pythia cookbook.  It still has some hooks in the `_config.yml` which mention pythia and link to bits and pieces of their website.  We should give some thought on how much of the pythia project we want to include, beyond the mention and credit that we're using their styling in the book build. 

in particular:
- [ ] navbar
- [ ] footers
- [ ] logos
- [ ] favicon

**Comment by amsnyder** [comment]
I think the TOC should mimic the folder structure. Maybe each folder should be a *part*. We will need explainer text either in the TOC or in an introductory chapter to describe what type of content is in each part. Here's an example for dataset_prepreprocessing (quick draft, defintely needs perfected):

> Sometimes data is published in file formats that are difficult or inefficient to work with. The HyTEST team often transforms our data inputs into more optimized formats, such as cloud optimized zarr stores. Because these optimized datasets are widely useful resources for the audience of this repository, we make them accessible to a larger audience, often through shared data storage, such as an S3 bucket. We upload the scripts that were used to transform these datasets from their source format into the optimized format in our dataset_preprocessing folder to improve transparency and reproducibility.

Within each part, we will might need chapters to group things together as archive, demos, tutorials (so that the reader understands what level of content they are getting. These will also need to be explained somewhere - here's a first draft of what you could use:
- archive – a script, workflow, or similar that was used to produce a shared resource (like a dataset). The purpose of these files is to ensure transparency and reproducibility of this shared resource.
- Demos – Demonstration of a technology/concept with minimally sufficient documentation of the process.
- Tutorials – Fully built out learning tutorials intended to be used as training material for someone unfamiliar with a concept/technology.

Then there might be another level of grouping inside that. For example, inside the dataset preprocessing/archive, we might have a section for CONUS404. In the model_evaluation/tutorials, we will want a section for the NWM evaluation that contains all of the notebooks.

So I guess to summarize, I am suggesting that we very much mimic the folder structure and make sure we have enough explainer text for someone new to understand what to expect in each grouping of content.

**Comment by gzt5142** [comment]
Closing this PR as un-merged. . . See #194
