### ISSUE TITLE
Documentation on reading from and writing to object storage

### ISSUE THREAD

**Issue by rsignell-usgs** [hytest-org/hytest#177]
As discussed today on the WIM call, it would really help our users (and us!) to have nice documentation on reading from and writing to s3-compatible object storage (which includes both AWS object storage and Open Storage Network (OSN).  

I have a notebook for pangeo.chs.usgs.gov here: 
https://code.chs.usgs.gov/pangeo/notebooks/pangeo-tutorial/-/blob/usgs_workshop_mar2020/notebooks/reading_writing_data.ipynb

and I started modifying that one for nebari.esipfed.org here: 
https://nebari.esipfed.org/hub/user-redirect/lab/tree/shared/users/rsignell/notebooks/testing/reading_writing_data.ipynb

and the info on how we work with OSN is here:
https://github.com/hytest-org/hytest/issues/90#issuecomment-1278923602

**Comment by gzt5142** [comment]
A primer on S3 is in the repo already... but was written a long time ago, before a lot of these details changed.  Worth including any of this?  Or should it be deleted in favor of what you're doing? 

https://github.com/hytest-org/hytest/blob/main/essential_reading/DataSources/Data_S3.ipynb

**Comment by rsignell-usgs** [comment]
@gzt5142 I didn't even know about this.  :(

I think that all looks good, so perhaps we just need to merge in the content above with the stuff that @alaws-USGS showed today.    

@gzt5142 maybe it's best for you to try doing that and then passing to @sfoks as an alpha tester?

**Comment by gzt5142** [comment]
@sfoks @rsignell-usgs @alaws-USGS 

OK... I updated that doc.  Changed it from an executable notebook to a static markdown file. 
Read the doc here: 
https://github.com/hytest-org/hytest/blob/gt-177-aws-read-write/essential_reading/DataSources/Data_S3.md

That doc covers S3 object storage only.  no mention of clusters or kubernetes.

If you want to correct or expand any of that material, just clone the `gt-177-aws-read-write` branch and push a commit to it.

**Comment by amsnyder** [comment]
I am adding info about writing to the osn pod. Gene has the fsspec fs set up for this:

````
fs_write = fsspec.filesystem(
    's3',
    profile='osn-renci',  ## This is the profile name you configured above.
    client_kwargs={'endpoint_url': 'https://renc.osn.xsede.org'}
)
```

Do you have an actual example of how you write to the pod? I would ideally liked to add instructions for how to write from
1) a dataset stored in memory
2) a file on your local computer
3) maybe a file from another location on the OSN pod that you want to write to a new location

If you have any code snippets that could help, that would be much appreciated!

**Comment by gzt5142** [comment]
> Do you have an actual example of how you write to the pod

Any interactions with the instantiated `filesystem` object takes place through its methods. 
Some examples are in `/model_evaluation/tutorials/nwm_streamflow/01_Data_Prep.ipynb`, which writes chunked data from in-memory xarray datasets to a zarr dataset. 

For the most general case, you can `map` an S3 object to a python file handle, then use it like any other file handle as you would for a local file system: 

```
fname='s3://rsignellbucket2/testing/outfile.zarr'
outfile=fs_write.get_mapper(fname)
xarray_dataset.to_zarr(outfile)
```
In this example, `outfile` can be used anywhere a file-like object is needed by the standard library.

For much lower level access, use `open()` much like you would for local files: 
```
with fs_write.open(fname, "w") as f
    f.write("sample text")
```

I don't think I've ever used that form...  I always use a mapper, since that works better for libraries like xarray and pandas. 

For file operations outside of a python script, the AWS command line tool is typically used, near as I can tell.  Never done it myself, so have no experience.
