### ISSUE TITLE
Writing to OSN pod with Rclone

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#192]
@rsignell-usgs suggested I look into [Rclone](https://rclone.org/) ([related issue](https://github.com/pangeo-data/pangeo/issues/243)) for transferring data between cloud providers. I am trying to use it to transfer data to the OSN pod, but I am receiving errors, and I think my configuration may be incorrectly set up.

**Comment by rsignell-usgs** [comment]
@amsnyder yes, it can be a bit tricky to set up the configuration for the Rclone remotes. 

 I set up my `nhgf-dev` remote in rclone to use environment variables for credentials, and since our stuff is requester-pays, I can transfer using any AWS credentials that allow requester-pays, defined by the default profile in my `~/.aws/credentials file` or via environment variables.

In the call below, the AWS credentials it's using are actually my `esip-qhub` credentials
``` 
rclone sync --s3-requester-pays \ 
nhgf-dev://nhgf-development/conus404/conus404_daily.zarr/time \
osn-renc://rsignellbucket2/testing/time
```

I didn't use my `nhgf` credentials for the `nhgf-dev` remote because they don't work unless you are on `doi.net` and I wanted to be able to run this anywhere.

Does this make sense?

**Comment by amsnyder** [comment]
Thanks Rich - I think I've got it working. I didn't test the nhgf credentials for requester-pays because my credentials are out of date, but I'll test that out once I get them updated. I was able to sync between one OSN pod location and another. I am curious if there's a reason you use sync instead of copy?

**Comment by rsignell-usgs** [comment]
I didn't use my `nhgf` credentials either -- I used my `esip-qhub` credentials to read from the nhgf requester pays bucket. 

I use sync because if something gets interrupted you can just issue the sync command again and it will make sure all the files in the dir and subdirs get there.
