### ISSUE TITLE
JupyterBook TOC Update

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#266]
JupyterBook TOC should be updated to include:
- probably everything in [essential_reading](https://github.com/hytest-org/hytest/tree/main/essential_reading) - but I am not super familiar with what is in here - maybe Gene can comment if there is anything that should be left out
- Probably all of the markdown files and ipynbs in [environment_set_up](https://github.com/hytest-org/hytest/tree/main/environment_set_up)
- from [dataset_catalog](https://github.com/hytest-org/hytest/tree/main/dataset_catalog): main hytest data catalog and readme, [Nested_catalogs_and_datasets.ipynb](https://github.com/hytest-org/hytest/blob/main/dataset_catalog/demos/Nested_catalogs_and_datasets.ipynb)
- everything in [dataset_access](https://github.com/hytest-org/hytest/tree/main/dataset_access). Question for Rich: is the regridding example in there something we want to publicize? Or does it need redone?
- from [dataset_preprocessing](https://github.com/hytest-org/hytest/tree/main/dataset_preprocessing) - wait for open PR to be merged before making suggestions
- from [evaluation](https://github.com/hytest-org/hytest/tree/main/evaluation): README, [Metrics_DScore_Suite_v1.ipynb ](https://github.com/hytest-org/hytest/blob/main/evaluation/Metrics_DScore_Suite_v1.ipynb), [Metrics_StdSuite_v1.ipynb](https://github.com/hytest-org/hytest/blob/main/evaluation/Metrics_StdSuite_v1.ipynb), both [stats usage examples](https://github.com/hytest-org/hytest/tree/main/evaluation/tutorials/stats), notebooks 00-03 for the [NWM streamflow tutorial](https://github.com/hytest-org/hytest/tree/main/evaluation/tutorials/nwm_streamflow).

Everyone - please take a look and make sure I'm not proposing to include anything that is not ready for sharing.

**Comment by gzt5142** [comment]
Related topic....   For a proper publishable book, we really need the 'front matter' material. I think it will be critical to get some copy prepared so that a reader will know if they are in the right place: 

* About HyTEST (who is it, what is the mandate, who funds it)
* How to Contribute (open an issue? fork the repo? send an email?)
* Roadmap (what data, workflows, features, etc are coming?  when?)

Most of that 'about' material can probably come from existing proposals or other collateral currently stashed in a sharepoint document.

And I'm calling that 'front matter', but it can go in the back also. And maybe we should get a better name than 'back matter' (that naming feels stiff).. open to suggestions.  Currently, the prototype includes back matter of the license and a boilerplate 'contributing' doc.

**Comment by sfoks** [comment]
After going through all of the documents and notebooks, this is so awesommmmmmeeeeeeeeeeee. So much excellent work, its fun to read it all together, great work Gene, Andrew, Amelia, Rich & Tim! 

Got some small and maybe bigger comments below!

1. [in the yml](https://github.com/hytest-org/hytest/blob/main/_toc.yml), under `caption: Environment Set-Up`, is the [`environment_set_up/Start_Dask_Cluster_PangeoCHS`](https://github.com/hytest-org/hytest/blob/main/environment_set_up/Start_Dask_Cluster_PangeoCHS.ipynb) up to date, its currently commented out in the TOC? If so, we should add it because we cover quickstart on pangeo.chs documentation and have it listed in the README.md in the Environment Setup chapter.  I have the same comment with [`Start_Dask_Cluster_TallGrass.ipynb`](https://github.com/hytest-org/hytest/blob/main/environment_set_up/Start_Dask_Cluster_Tallgrass.ipynb).
2. In the [README.md](https://github.com/hytest-org/hytest/blob/main/environment_set_up/README.md), what's "CTek" and should we provide a link to it for submitting an issue?
3. I see `environment_set_up/clusters` in the toc, but its probably in another branch? It's not referenced in the README.md, should it be?
4. The link at the end of the 2nd paragraph in the credentialed access section on the [Data_S3.md](https://github.com/hytest-org/hytest/blob/main/essential_reading/DataSources/Data_S3.md#credentialed-access) looks like its missing a ']' on 'command line'.
5. I could see adding the [nested catalog ipynb](https://github.com/hytest-org/hytest/blob/main/dataset_catalog/demos/Nested_catalogs_and_datasets.ipynb) to the TOC under `dataset access` section and comment it out for now (currently it has an error in it on the main branch version).
6. We may want a `data handling` section after `dataset access`. I think under this section, we want to house the examples of how to take data from intake/source and common processing steps/workflows that users do with data with respect to space, time, taking slices out to view/explore, rechunk, resample, etc. So I envision everything in [here](https://github.com/hytest-org/hytest/tree/main/dataset_access) to be in `data handling`.
7. [`dataset_preprocessing/chunk`](https://github.com/hytest-org/hytest/blob/main/dataset_preprocessing/chunk.md) looks blank, maybe this is filled out in a branch though and I'm just missing this? I could see the introduction material in the [`dataset_preprocessing/ReChunkingData.ipynb`](https://github.com/hytest-org/hytest/blob/main/dataset_preprocessing/ReChunkingData.ipynb) being pasted into the chunk.md if needed.
8. In the section `Evaluation Tutorials`, and after the streamflow eval section, let's put the CONUS404 evaluation. I guess first the [data prep for CONUS404](https://github.com/hytest-org/hytest/blob/main/dataset_preprocessing/tutorials/CONUS404/1_CONUS404_DRB_Data_Prep.ipynb) and then [analysis](https://github.com/hytest-org/hytest/blob/main/evaluation/tutorials/CONUS404/conus404_analysis.ipynb) (could be commented it out until its ready?) and then viz commented out in the TOC? 

low priority:
1. This is currently not in the _toc.yml but I wanted to double check anyway if this information is still relevant regarding the NetCDF model in the [gdp_data_prep.md](https://github.com/hytest-org/hytest/blob/main/essential_reading/gdp_data_prep.md) markdown, looks like it was created 2015? Also are datasets still being submitted to the Geo Data Portal? Maybe that's a Dave Q. Do we have a spot for deprecated .md docs?
2. I like that the [STAC markdown](https://github.com/hytest-org/hytest/blob/main/essential_reading/DataSources/Data_STAC.md) is present in the essential readings data sources because it gives folks a preview of what's coming. We could add a brief explanation of what STAC is with links, but not a priority at this point.

**Comment by gzt5142** [comment]
> 3\. I see `environment_set_up/clusters`

AHA !!!

I can see clearly now. 

@amsnyder  -- I now understand why that mostly-empty document was there. . .  

It is needed by the jupyterbook TOC as a 'container' to hold children in the book's structure. I have not found a way (despite a lot of trying) to avoid having to do this. In the `_toc.yml`: 

```
  - file: environment_set_up/clusters
    sections:
    - file: environment_set_up/Help_AWS_Credentials
    - file: environment_set_up/Start_Dask_Cluster_Nebari  
    - file: environment_set_up/Start_Dask_Cluster_Denali
```  

That clusters document was needed to provide a container (and a title) to the section/sub-section with all of the various cluster options. 

So..... we need to put it back.  I completely missed its importance when you suggested removing an 'empty' file. 

Now... I put it in as an empty, but we can sure put some text in there, so we don't get confused in future. 

--gt

**Comment by amsnyder** [comment]
> After going through all of the documents and notebooks, this is so awesommmmmmeeeeeeeeeeee. So much excellent work, its fun to read it all together, great work Gene, Andrew, Amelia, Rich & Tim!
> 
> Got some small and maybe bigger comments below!
> 
> 1. [in the yml](https://github.com/hytest-org/hytest/blob/main/_toc.yml), under `caption: Environment Set-Up`, is the [`environment_set_up/Start_Dask_Cluster_PangeoCHS`](https://github.com/hytest-org/hytest/blob/main/environment_set_up/Start_Dask_Cluster_PangeoCHS.ipynb) up to date, its currently commented out in the TOC? If so, we should add it because we cover quickstart on pangeo.chs documentation and have it listed in the README.md in the Environment Setup chapter.  I have the same comment with [`Start_Dask_Cluster_TallGrass.ipynb`](https://github.com/hytest-org/hytest/blob/main/environment_set_up/Start_Dask_Cluster_Tallgrass.ipynb).
> 2. In the [README.md](https://github.com/hytest-org/hytest/blob/main/environment_set_up/README.md), what's "CTek" and should we provide a link to it for submitting an issue?
> 3. I see `environment_set_up/clusters` in the toc, but its probably in another branch? It's not referenced in the README.md, should it be?
> 4. The link at the end of the 2nd paragraph in the credentialed access section on the [Data_S3.md](https://github.com/hytest-org/hytest/blob/main/essential_reading/DataSources/Data_S3.md#credentialed-access) looks like its missing a ']' on 'command line'.
> 5. I could see adding the [nested catalog ipynb](https://github.com/hytest-org/hytest/blob/main/dataset_catalog/demos/Nested_catalogs_and_datasets.ipynb) to the TOC under `dataset access` section and comment it out for now (currently it has an error in it on the main branch version).
> 6. We may want a `data handling` section after `dataset access`. I think under this section, we want to house the examples of how to take data from intake/source and common processing steps/workflows that users do with data with respect to space, time, taking slices out to view/explore, rechunk, resample, etc. So I envision everything in [here](https://github.com/hytest-org/hytest/tree/main/dataset_access) to be in `data handling`.
> 7. [`dataset_preprocessing/chunk`](https://github.com/hytest-org/hytest/blob/main/dataset_preprocessing/chunk.md) looks blank, maybe this is filled out in a branch though and I'm just missing this? I could see the introduction material in the [`dataset_preprocessing/ReChunkingData.ipynb`](https://github.com/hytest-org/hytest/blob/main/dataset_preprocessing/ReChunkingData.ipynb) being pasted into the chunk.md if needed.
> 8. In the section `Evaluation Tutorials`, and after the streamflow eval section, let's put the CONUS404 evaluation. I guess first the [data prep for CONUS404](https://github.com/hytest-org/hytest/blob/main/dataset_preprocessing/tutorials/CONUS404/1_CONUS404_DRB_Data_Prep.ipynb) and then [analysis](https://github.com/hytest-org/hytest/blob/main/evaluation/tutorials/CONUS404/conus404_analysis.ipynb) (could be commented it out until its ready?) and then viz commented out in the TOC?
> 
> low priority:
> 
> 1. This is currently not in the _toc.yml but I wanted to double check anyway if this information is still relevant regarding the NetCDF model in the [gdp_data_prep.md](https://github.com/hytest-org/hytest/blob/main/essential_reading/gdp_data_prep.md) markdown, looks like it was created 2015? Also are datasets still being submitted to the Geo Data Portal? Maybe that's a Dave Q. Do we have a spot for deprecated .md docs?
> 2. I like that the [STAC markdown](https://github.com/hytest-org/hytest/blob/main/essential_reading/DataSources/Data_STAC.md) is present in the essential readings data sources because it gives folks a preview of what's coming. We could add a brief explanation of what STAC is with links, but not a priority at this point.
> 
> Instead of front matter, maybe its 'About' and 'back matter' can be 'Supplementary'. In this backmatter section, we likely need a disclaimer (if not on the front page?).

Thanks for doing a detailed review @sfoks. I've moved some of your suggestions into separate issues (2 -> #272, 3 -> #274, 4 -> #273) so that we can keep this thread focused on which files the TOC should point to.

For 1 - I think these are helper functions that are referenced in [environment_set_up/README.md](https://github.com/hytest-org/hytest/blob/main/environment_set_up/README.md). I would want this README.md to be the opener for the environment_set_up section. I'm not sure we need to put them in the book as chapters since the content of the notebook isn't very interesting, but happy to hear if others feel differently.

For 3 - these are referenced in . Do you think we need them to be in their own chapter?

For 5 - I think this could be a valuable addition - I will add it to the list I put at the top. @sfoks - can you open a new issue detailing any error you are seeing that needs fixed?

Foor 6- @sfoks can we just rename this folder? this was a part of the proposed contents at the top of this issue

For 8 - we want to include this, but @alaws-USGS says the content won't be ready for a month, and we don't have the files on Github in the right place, which is why I left it out for now (see #214). We can handle new content additions as they become available - this is meant to be a list of content that we can build a book from today.

As for gdp_data_prep.md - this content is not currently in a polished format for the book.

let's leave out the STAC.md too. I'd like to get a working version of the book with content we currently have to keep things moving forward.

**Comment by gzt5142** [comment]
> 1. [in the yml](https://github.com/hytest-org/hytest/blob/main/_toc.yml), under `caption: Environment Set-Up`, is the [`environment_set_up/Start_Dask_Cluster_PangeoCHS`](https://github.com/hytest-org/hytest/blob/main/environment_set_up/Start_Dask_Cluster_PangeoCHS.ipynb) up to date, its currently commented out in the TOC? If so, we should add it because we cover quickstart on pangeo.chs documentation and have it listed in the README.md in the Environment Setup chapter.  I have the same comment with [`Start_Dask_Cluster_TallGrass.ipynb`](https://github.com/hytest-org/hytest/blob/main/environment_set_up/Start_Dask_Cluster_Tallgrass.ipynb).

Those are commented out simply because the book got built on nebari... so starting a cluster appropriate for tallgrass or pangeo.chs is tricky to do on nebari.  Can do... but I commented them out initially so as to just get the prototype done.
