### ISSUE TITLE
populate clusters.md

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#274]
Need to add a `clusters.md` file in `environment_set_up` to describe the following files:

```
environment_set_up/Help_AWS_Credentials
environment_set_up/Help_VerifyAWS_wCluster.ipynb
environment_set_up/Start_Dask_Cluster_Nebari  
environment_set_up/Start_Dask_Cluster_Denali
environment_set_up/Start_Dask_Cluster_Tallgrass
environment_set_up/Start_Dask_Cluster_PangeoCHS
```

A link to this md file should replace the ending of [environment_set_up/README.md](https://github.com/hytest-org/hytest/blob/main/environment_set_up/README.md)

**Comment by gzt5142** [comment]
For sure to include these sections... there's a bit of a trick to it, given that we build the jupyter-book in one environments, but those different cluster configurations are specific to different (sometimes incompatible) other environments. 

I have some thoughts to make this work, but it will be non-standard. the two that I see are: 
1) Make a non-executable version of the problematic notebooks.  This will involve some duplication of content in the repo... but only one doc gets included in the book. This amounts to writing a 'ghost' document for `Start_Dask_Cluster` **just** for the TOC to render. 
2) Manipulate the jupyterbook cache -- run the relevant notebook in its native environment, then patch the cache into the one on nebari so that it won't try to build these extra notebooks. 

There  may be other options.  The easiest for sure is number one. We can style the markdown such that it looks just like it was an executed notebook for purposes of the book.

**Comment by amsnyder** [comment]
@gzt5142 is there any way to include a non-executed version of the notebook in the TOC? (without making a new copy - just telling JB build not to execute them)

**Comment by gzt5142** [comment]
> @gzt5142 is there any way to include a non-executed version of the notebook in the TOC? (without making a new copy - just telling JB build not to execute them)

Not that I'm aware.... The solution I recommend is (1) in the above comment: Create a 'ghost' version of the notebook in pure markdown.  This is solely for JB rendering purposes.

**Comment by amsnyder** [comment]
I feel a little hesistant to make duplicate copies of information that need to stay in sync...but I guess that's our best option for now. Would you be able to create those?
