### ISSUE TITLE
Improve repository documentation

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#50]
Starting an issue to work out the details of improving our documentation for this repository. I really liked the demo of JupyterBook that @gzt5142 gave yesterday, and I'm on board with using that. I think we have some other details to work out which we can talk through here.

**Comment by amsnyder** [comment]
I have also been thinking about how we can better document our files. I was imagining a README.md inside every/most folders to describe the contents of each file/folder. For each notebook, I think it would be helpful to document these three things in some formal way:
- inputs (format/storage location)
- does the notebook do/why should we care?
- outputs (format/storage location)

I'm curious if others have thoughts on what information we should be tracking for every notebook?

And I'd like to know form @gzt5142 if writing this in a README.md file is the best way to build a JupyterBook or if you have a better suggestion?

**Comment by gzt5142** [comment]
Couple of things to talk about here... chewy stuff...  

### First... 
documenting the repo can be done a few ways, and it kind of depends on what the goals are as to which is best. Here are three common options that I have used in past: 
- Put `.md` files in the repo alongside what they are meant to describe.  That amounts to a `README` per folder, more or less. For small-ish projects, I usually start with this, because it is easy, fast, and simple to implement. 
- Use the built-in **wiki** functionality that comes with github repos. This is tracked on github and not in the file repo itself... so some maintenance headaches. Wikis are really easy to write/format, and are a good choice if what we're documenting is how to use the repo (both as a contributor or as a consumer).
- Build a jupyterbook (or similar) `./doc` folder in the repo. Full-fledged, rich documentation, with bells/whistles.


### Second...
For documenting a given notebook as to what it does, why we care, etc... I would put that right in the notebook itself. If it is in a separate file/place, then we run the risk that the docs and the notebook code are out of sync.  Together, that's less of a risk. 

This can be done with a 'dropdown' element so that it isn't always visible, but the user can toggle to see/read if they want.  You can see an example of that in the [chunking example](https://gzt5142.github.io/hytest-workbook/L2/Pre/ReChunkingData.html) from yesterday's demo. 

I put in a stub to show objectives for the student... This could also easily be a what/why/who blurb.  Alternately, that sort of text can go as an unstyled block at the bottom of the notebook.

**Comment by gzt5142** [comment]
> For documenting a given notebook as to what it does, why we care, etc... I would put that right in the notebook itself.

We also have a range of metadata options for notebooks.  Metadata is less visible -- which can either be an advantage or a disadvantage, I suppose. JupyterBook has some hooks into metadata <https://jupyterbook.org/en/stable/content/metadata.html> , which maybe we could leverage if we go the Book route on overall docs.

**Comment by gzt5142** [comment]
> And I'd like to know form @gzt5142 if writing this in a README.md file is the best way to build a JupyterBook

JupyterBook compiler understands markdown, so `README.md` or `AboutThisNotebook.md` would work just fine.  JupyterBook also understands other formatting, including LaTex... which is probably WAY more than you want for this application.  A middle ground is a slightly richer markdown <https://jupyterbook.org/en/stable/content/myst.html>.... 

My recommendation is to use what you know -- likely markdown -- to get started.  Get something written immediately. The main problem with documentation, IMO, isn't that it isn't formatted well, it's that it doesn't exist. So anything we can capture in a simple markdown will be very helpful.  Can translate to richer formats as a value-add later.

**Comment by amsnyder** [comment]
I agree with your point that we should include what a notebook does and why we should care in the notebook itself. But I also think this information is useful to a user browsing our resources, who may not want to open every notebook to see what it does.

I need to get more familiar with JupyterBook, but it sounds like we could get the best of both worlds with tags, right? Maybe we start every notebook with a cell that has standard information, and then we tag it and harvest it into the JupyterBook? I'll play around with JupyterBook to get more familiar with its functionality.

**Comment by gzt5142** [comment]
Ah... I understand better now .... 

It might be useful for a 'broad-strokes' or a summary document in a folder to include such information about the notebooks in the same folder. This would fit with JupyterBook very nicely, I think.   We could do it by hand -- editing a TOC or README doc... or we might be able to have jupyterbook build it for us using notebook metadata or other notebook content. That would be pretty slick, I think.... but would require some deeper investigation and a little coding to make that work.

**Comment by gzt5142** [comment]
> it sounds like we could get the best of both worlds with tags, right? Maybe we start every notebook with a cell that has standard information, and then we tag it and harvest it into the JupyterBook?

I think this is right. 

I will spend some time today to better understand tagging and how to harvest tagged data as part of the book building process.  

I'll start a separate thread on that specific issue.

**Comment by gzt5142** [comment]
I'm finding this to be more challenging/complicated than originally thought. Given the small-ish size of the project, I now am of the opinion that a manually-curated summary document with abstracts of each notebook is going to be a better return on time invested.  Certainly as a first pass. Add automation once the project gains size.  

??

**Comment by gzt5142** [comment]
This issue is addressed in #194 .  Close when that merges
